#pragma once
#include <Adafruit_GFX.h>

#include <math.h>

#include "icons/IconBitmaps.h"

// Icons: real Lucide glyphs rasterized to 1-bit bitmaps (see
// icons/IconBitmaps.h, generated by scripts/gen_icons.py) — the same
// source crosspoint-reader draws its icons from. Bitmaps are square
// (IconBitmaps::ICON_SIZE) and drawn centered on (cx, cy); drawBitmap()
// only plots the "ink" pixels, so whatever's already at (cx, cy) — a
// selected row's black fill or an unselected row's white — shows through
// everywhere else, no separate background color needed.
class Icons {
 public:
  static void draw(Adafruit_GFX& g, int cx, int cy, const uint8_t* bitmap, uint16_t color) {
    int half = IconBitmaps::ICON_SIZE / 2;
    g.drawBitmap(cx - half, cy - half, bitmap, IconBitmaps::ICON_SIZE, IconBitmaps::ICON_SIZE,
                 color);
  }

  // Same, at the smaller chrome-scale size (IconBitmaps::ICON_SIZE_SMALL) —
  // for spots too tight for the full menu-icon size, like the header.
  static void drawSmall(Adafruit_GFX& g, int cx, int cy, const uint8_t* bitmap, uint16_t color) {
    int half = IconBitmaps::ICON_SIZE_SMALL / 2;
    g.drawBitmap(cx - half, cy - half, bitmap, IconBitmaps::ICON_SIZE_SMALL,
                 IconBitmaps::ICON_SIZE_SMALL, color);
  }

  static void wifi(Adafruit_GFX& g, int cx, int cy, uint16_t color) {
    draw(g, cx, cy, IconBitmaps::wifi, color);
  }

  // Header status icons (small variants): moon for "idle-sleep applies on
  // this screen", zap for "USB connected".
  static void moonSmall(Adafruit_GFX& g, int cx, int cy, uint16_t color) {
    drawSmall(g, cx, cy, IconBitmaps::moon_sm, color);
  }
  static void zapSmall(Adafruit_GFX& g, int cx, int cy, uint16_t color) {
    drawSmall(g, cx, cy, IconBitmaps::zap_sm, color);
  }

  // Picks an icon by the config-facing key string ("bulb"/"toggle"/"moon"/
  // "lock"/"fan"/"thermometer"/"tv"); unrecognized or empty keys fall back
  // to the generic bolt (lucide: zap).
  static void byKey(Adafruit_GFX& g, int cx, int cy, uint16_t color, const String& key) {
    if (key == "bulb") {
      draw(g, cx, cy, IconBitmaps::lightbulb, color);
    } else if (key == "toggle") {
      draw(g, cx, cy, IconBitmaps::toggle_right, color);
    } else if (key == "moon") {
      draw(g, cx, cy, IconBitmaps::moon, color);
    } else if (key == "lock") {
      draw(g, cx, cy, IconBitmaps::lock, color);
    } else if (key == "fan") {
      draw(g, cx, cy, IconBitmaps::fan, color);
    } else if (key == "thermometer") {
      draw(g, cx, cy, IconBitmaps::thermometer, color);
    } else if (key == "tv") {
      draw(g, cx, cy, IconBitmaps::tv, color);
    } else {
      draw(g, cx, cy, IconBitmaps::zap, color);
    }
  }

  // Rotating-dot spinner: `frame` picks which of 8 dots around the ring is
  // the "active" (filled) one. Advance frame each animation tick to spin it.
  static void spinner(Adafruit_GFX& g, int cx, int cy, int radius, int frame) {
    constexpr int DOTS = 8;
    for (int i = 0; i < DOTS; i++) {
      float angle = (2.0f * PI * i) / DOTS - PI / 2.0f;
      int dx = cx + (int)(radius * cosf(angle));
      int dy = cy + (int)(radius * sinf(angle));
      if (i == frame % DOTS) {
        g.fillCircle(dx, dy, 5, GxEPD_BLACK);
      } else {
        g.drawCircle(dx, dy, 2, GxEPD_BLACK);
      }
    }
  }

  // Two chevrons, one up one down — footer hint for the "move selection"
  // button (next/previous row).
  static void upDown(Adafruit_GFX& g, int cx, int cy, int s, uint16_t color) {
    int gap = 2;
    g.fillTriangle(cx, cy - gap - s, cx - s, cy - gap, cx + s, cy - gap, color);
    g.fillTriangle(cx, cy + gap + s, cx - s, cy + gap, cx + s, cy + gap, color);
  }
};
